version: '3'

services:
  app:
    build: .
    entrypoint: [entrypoint.sh]
    depends_on:
      - db
    ports:
      - 7001:7001
  db:
    image: postgres
    restart: always
    ports:
      - '5432'
    environment:
      - POSTGRES_DB=bipu
      - POSTGRES_PASSWORD=bipubipu
      - POSTGRES_USER=root
